// Concord plugin protocol v1 — Remediator service.
// A Remediator plugin executes a state-changing action against a vendor
// API to fix a failing finding. The host invokes it only after an
// operator explicitly opts in via `concord remediate <finding> --execute`.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/concord/plugin/v1/remediator.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Remediator_Capabilities_FullMethodName = "/concord.plugin.v1.Remediator/Capabilities"
	Remediator_DryRun_FullMethodName       = "/concord.plugin.v1.Remediator/DryRun"
	Remediator_Execute_FullMethodName      = "/concord.plugin.v1.Remediator/Execute"
)

// RemediatorClient is the client API for Remediator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemediatorClient interface {
	// Capabilities advertises the actions this remediator can perform.
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*RemediatorCapabilitiesResponse, error)
	// DryRun returns the operations the remediator would perform without
	// executing them. The host MUST show this to the operator before
	// calling Execute.
	DryRun(ctx context.Context, in *RemediateRequest, opts ...grpc.CallOption) (*RemediateResponse, error)
	// Execute performs the remediation. Returns a structured audit trail
	// (resource ids touched, before/after state) the host writes to the
	// audit_event log.
	Execute(ctx context.Context, in *RemediateRequest, opts ...grpc.CallOption) (*RemediateResponse, error)
}

type remediatorClient struct {
	cc grpc.ClientConnInterface
}

func NewRemediatorClient(cc grpc.ClientConnInterface) RemediatorClient {
	return &remediatorClient{cc}
}

func (c *remediatorClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*RemediatorCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemediatorCapabilitiesResponse)
	err := c.cc.Invoke(ctx, Remediator_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remediatorClient) DryRun(ctx context.Context, in *RemediateRequest, opts ...grpc.CallOption) (*RemediateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemediateResponse)
	err := c.cc.Invoke(ctx, Remediator_DryRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remediatorClient) Execute(ctx context.Context, in *RemediateRequest, opts ...grpc.CallOption) (*RemediateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemediateResponse)
	err := c.cc.Invoke(ctx, Remediator_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemediatorServer is the server API for Remediator service.
// All implementations must embed UnimplementedRemediatorServer
// for forward compatibility.
type RemediatorServer interface {
	// Capabilities advertises the actions this remediator can perform.
	Capabilities(context.Context, *CapabilitiesRequest) (*RemediatorCapabilitiesResponse, error)
	// DryRun returns the operations the remediator would perform without
	// executing them. The host MUST show this to the operator before
	// calling Execute.
	DryRun(context.Context, *RemediateRequest) (*RemediateResponse, error)
	// Execute performs the remediation. Returns a structured audit trail
	// (resource ids touched, before/after state) the host writes to the
	// audit_event log.
	Execute(context.Context, *RemediateRequest) (*RemediateResponse, error)
	mustEmbedUnimplementedRemediatorServer()
}

// UnimplementedRemediatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemediatorServer struct{}

func (UnimplementedRemediatorServer) Capabilities(context.Context, *CapabilitiesRequest) (*RemediatorCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedRemediatorServer) DryRun(context.Context, *RemediateRequest) (*RemediateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DryRun not implemented")
}
func (UnimplementedRemediatorServer) Execute(context.Context, *RemediateRequest) (*RemediateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedRemediatorServer) mustEmbedUnimplementedRemediatorServer() {}
func (UnimplementedRemediatorServer) testEmbeddedByValue()                    {}

// UnsafeRemediatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemediatorServer will
// result in compilation errors.
type UnsafeRemediatorServer interface {
	mustEmbedUnimplementedRemediatorServer()
}

func RegisterRemediatorServer(s grpc.ServiceRegistrar, srv RemediatorServer) {
	// If the following call pancis, it indicates UnimplementedRemediatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Remediator_ServiceDesc, srv)
}

func _Remediator_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediatorServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Remediator_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediatorServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remediator_DryRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemediateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediatorServer).DryRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Remediator_DryRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediatorServer).DryRun(ctx, req.(*RemediateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Remediator_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemediateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemediatorServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Remediator_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemediatorServer).Execute(ctx, req.(*RemediateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Remediator_ServiceDesc is the grpc.ServiceDesc for Remediator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Remediator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "concord.plugin.v1.Remediator",
	HandlerType: (*RemediatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Capabilities",
			Handler:    _Remediator_Capabilities_Handler,
		},
		{
			MethodName: "DryRun",
			Handler:    _Remediator_DryRun_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Remediator_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/concord/plugin/v1/remediator.proto",
}
