#!/usr/bin/env bash
#
# setup-dev-workspace.sh — generate a Go workspace (go.work) at the parent
# directory that unifies the Concord core modules for local development.
#
# Why: concord-platform and the CLI import sibling modules (concord,
# concord-workflow, concord-plugin-sdk) that are not yet published as tagged
# versions. Per-module builds already work via the `replace` directives in each
# go.mod; this workspace additionally lets you build/test ACROSS repos at once
# (e.g. change the SDK and rebuild the platform without editing go.mod).
#
# The go.work lives at the workspace root (the parent of these repos), which is
# not itself a git repo — so it is a local, regenerable artifact, not committed.
# Run this once after cloning the sibling repos next to each other:
#
#   development/
#     concord/               <- this repo
#     concord-platform/
#     concord-workflow/
#     concord-plugin-sdk/
#
# Usage:  ./scripts/setup-dev-workspace.sh
set -euo pipefail

# Resolve the workspace root = parent of this repo.
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ws_root="$(cd "${repo_root}/.." && pwd)"

# The core modules that depend on each other. Content packs and plugins depend
# only on the (soon-to-be-published) SDK and are intentionally excluded.
modules=(concord concord-plugin-sdk concord-platform concord-workflow)

present=()
for m in "${modules[@]}"; do
  if [[ -f "${ws_root}/${m}/go.mod" ]]; then
    present+=("./${m}")
  else
    echo "warning: ${ws_root}/${m} not found — clone it next to this repo for a full workspace" >&2
  fi
done

if [[ ${#present[@]} -eq 0 ]]; then
  echo "error: no core modules found under ${ws_root}" >&2
  exit 1
fi

work_file="${ws_root}/go.work"
{
  echo "// Generated by concord/scripts/setup-dev-workspace.sh — local dev only, do not publish."
  echo "go 1.25.11"
  echo ""
  echo "use ("
  for p in "${present[@]}"; do echo "	${p}"; done
  echo ")"
} > "${work_file}"

echo "wrote ${work_file}:"
sed 's/^/  /' "${work_file}"
echo ""
echo "Now: cd ${ws_root} && GOWORK=${work_file} go build ./concord-platform/..."
echo "(or export GOWORK once, or just work from the workspace root)"
